server:
  port: 9002
spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  main:
    banner-mode: "off"
#配置eureka
eureka:
  client:
    service-url:
      # 多个Eureka server之间用逗号隔开
      defaultZone: http://localhost:9000/eureka, http://localhost:8000/eureka
  instance:
    prefer-ip-address: true