server:
  port: 9002
spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  main:
    banner-mode: "off"
  cloud:
    loadbalancer:
      retry:
        enabled: true
#配置eureka
eureka:
  client:
    service-url:
      # 多个Eureka server之间用逗号隔开
      defaultZone: http://localhost:9000/eureka, http://localhost:8000/eureka
  instance:
    prefer-ip-address: true
#全局debug
logging:
  level:
    root: debug
#    修改ribbon的负载均衡策略 服务名 - ribbon - NFLoadBalancerRuleClassName: 策略
service-product:
  ribbon:
  #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    ConnectTimeout: 2500 # Ribbon的连接超时时间, 我测试不生效
    ReadTimeout: 1000 # Ribbon的数据读取超时时间, 我测试不生效
    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
    MaxAutoRetries: 0 # 对当前实例的重试次数
