server:
  port: 9003
spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  main:
    banner-mode: "off"
#配置eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
    instance:
      prefer-ip-address: true # 使用ip地址注册
feign:
  client:
    config:
      # 要请求的服务, 即配置在@FeignClient name字段内的值
      service-product:
#        NONE 不输出日志, 性能最高
#        BASIC 适用于生产环境追踪问题
#        HEADERS 在BASIC的基础上, 记录请求和响应头
#        FULL 记录所有
        loggerLevel: FULL
        connectTimeout: 3000
        readTimeout: 3000
  hystrix:
    enabled: true # 开启对Hystrix的支持
logging:
  level:
    cn.itcast.order.feign.ProductFeignClient: debug
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #连接超时时间, 默认为1000ms