#模拟2个EurekaServer
# 端口9000, 8000
# 2个server需要互相注册

spring:
  application:
    name: eureka-server
  main:
    banner-mode: "off"
eureka:
  instance:
    hostname: localhost
  client:
    # 现在需要 注册自己到注册中心了
    register-with-eureka: true
    # 现在需要 从eureka中获取注册信息
    fetch-registry: true
---
spring:
  profiles: 9000
server:
  port: 9000
eureka:
  client:
    service-url:
#      端口9000的server要注册8000的
      defaultZone: http://localhost:8000/eureka
---
spring:
  profiles: 8000
server:
  port: 8000
eureka:
  client:
    service-url:
#      端口8000的server要注册9000的
      defaultZone: http://localhost:9000/eureka