server:
  port: 7003 #服务端口
spring:
  application:
    name: rabbitmq-consumer-2 #指定服务名
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input: # 内置的获取消息的通道, 从itcast-default中获取消息
          destination: itcast-default
        myinput:
          destination: itcase-custom-output
          group: group1 #设置消息的组名称(同名组中的多个消费者, 只有一个会消费消息)
          consumer:
            partitioned: true #开启分区支持
      binders:
        defaultRabbit:
          type: rabbit
      instance-count: 2 #消费者总数
      instance-index: 1 #当前消费者的索引