spring:
  application:
    name: api-gateway-server
  redis:
    host: localhost
    pool: 6379
    database: 0
  cloud:
    #配置Spring Cloud Gateway的路由
    gateway:
      routes:
        #配置路由: 路由id, 路由到微服务的uri, 断言(判断条件)
        - id: product-service # 保持唯一即可
          # uri: http://127.0.0.1:9001 # 目标微服务请求地址
          uri: lb://service-product # 根据微服务名称从注册中心中拉取服务请求路径
          predicates:
            # 需要重写转发路径
            - Path=/product-service/**
          filters: #配置路由过滤器
            # 使用限流过滤器, 是Spring Cloud Gateway提供的
            - name: RequestRateLimiter
              args:
                # 使用SpEL从容器中获取对象
                # 指定为限流的标准
                key-resolver: '#{@pathKeyResolver}'
#                key-resolver: '#{@userKeyResolver}'
                # 参数 replenishRate: 向令牌桶中填充的速率
                redis-rate-limiter.replenishRate: 1
                # burstCapacity: 令牌桶的容量
                redis-rate-limiter.burstCapacity: 3
            - RewritePath=/product-service/(?<segment>.*), /$\{segment} #路径重写的过滤器, 在yml中$写为$\

# eureka注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
    instance:
      prefer-ip-address: true # 使用ip地址注册
---
spring:
  profiles: 8084
server:
  port: 8084
---
spring:
  profiles: 8083
server:
  port: 8083